/** Generated by `node scripts/school-units.mjs registry` — every written unit of this grade. */
import type { QuizQuestion } from '../../../types';
import { GRADE2_ENGLISH_CLOTHES_AND_WEATHER } from './english-clothes-and-weather';
import { GRADE2_ENGLISH_HEALTHY_FOOD } from './english-healthy-food';
import { GRADE2_ENGLISH_MY_BODY } from './english-my-body';
import { GRADE2_ENGLISH_MY_FAMILY } from './english-my-family';
import { GRADE2_ENGLISH_MY_HOUSE } from './english-my-house';
import { GRADE2_ENGLISH_PETS_AND_MONSTERS } from './english-pets-and-monsters';
import { GRADE2_ENGLISH_TOYS } from './english-toys';
import { GRADE2_GREEK_ACCENTS } from './greek-accents';
import { GRADE2_GREEK_ADJECTIVES } from './greek-adjectives';
import { GRADE2_GREEK_NOUNS_ARTICLES } from './greek-nouns-articles';
import { GRADE2_GREEK_PUNCTUATION } from './greek-punctuation';
import { GRADE2_GREEK_READING } from './greek-reading';
import { GRADE2_GREEK_SPELLING_BASICS } from './greek-spelling-basics';
import { GRADE2_GREEK_VERBS_TIME } from './greek-verbs-time';
import { GRADE2_MATH_ADD_SUBTRACT_TO_100 } from './math-add-subtract-to-100';
import { GRADE2_MATH_CLOCK_AND_TIME } from './math-clock-and-time';
import { GRADE2_MATH_EURO_MONEY } from './math-euro-money';
import { GRADE2_MATH_INTRO_TIMES_TABLES } from './math-intro-times-tables';
import { GRADE2_MATH_MEASURE_LENGTH_WEIGHT } from './math-measure-length-weight';
import { GRADE2_MATH_NUMBERS_TO_100 } from './math-numbers-to-100';
import { GRADE2_MATH_SHAPES_AND_SOLIDS } from './math-shapes-and-solids';
import { GRADE2_SCIENCE_ANIMALS } from './science-animals';
import { GRADE2_SCIENCE_LIVING_NONLIVING_ENERGY_TRANSPORT } from './science-living-nonliving-energy-transport';
import { GRADE2_SCIENCE_PLACES_OF_GREECE } from './science-places-of-greece';
import { GRADE2_SCIENCE_PLANTS } from './science-plants';
import { GRADE2_SCIENCE_SCHOOL_NEIGHBOURHOOD_ORIENTATION } from './science-school-neighbourhood-orientation';
import { GRADE2_SCIENCE_TIME_NEEDS_RIGHTS } from './science-time-needs-rights';
import { GRADE2_SCIENCE_WATER_WEATHER } from './science-water-weather';

export const QUESTIONS: Record<string, QuizQuestion[]> = {
  '2/english/clothes-and-weather': GRADE2_ENGLISH_CLOTHES_AND_WEATHER,
  '2/english/healthy-food': GRADE2_ENGLISH_HEALTHY_FOOD,
  '2/english/my-body': GRADE2_ENGLISH_MY_BODY,
  '2/english/my-family': GRADE2_ENGLISH_MY_FAMILY,
  '2/english/my-house': GRADE2_ENGLISH_MY_HOUSE,
  '2/english/pets-and-monsters': GRADE2_ENGLISH_PETS_AND_MONSTERS,
  '2/english/toys': GRADE2_ENGLISH_TOYS,
  '2/greek/accents': GRADE2_GREEK_ACCENTS,
  '2/greek/adjectives': GRADE2_GREEK_ADJECTIVES,
  '2/greek/nouns-articles': GRADE2_GREEK_NOUNS_ARTICLES,
  '2/greek/punctuation': GRADE2_GREEK_PUNCTUATION,
  '2/greek/reading': GRADE2_GREEK_READING,
  '2/greek/spelling-basics': GRADE2_GREEK_SPELLING_BASICS,
  '2/greek/verbs-time': GRADE2_GREEK_VERBS_TIME,
  '2/math/add-subtract-to-100': GRADE2_MATH_ADD_SUBTRACT_TO_100,
  '2/math/clock-and-time': GRADE2_MATH_CLOCK_AND_TIME,
  '2/math/euro-money': GRADE2_MATH_EURO_MONEY,
  '2/math/intro-times-tables': GRADE2_MATH_INTRO_TIMES_TABLES,
  '2/math/measure-length-weight': GRADE2_MATH_MEASURE_LENGTH_WEIGHT,
  '2/math/numbers-to-100': GRADE2_MATH_NUMBERS_TO_100,
  '2/math/shapes-and-solids': GRADE2_MATH_SHAPES_AND_SOLIDS,
  '2/science/animals': GRADE2_SCIENCE_ANIMALS,
  '2/science/living-nonliving-energy-transport': GRADE2_SCIENCE_LIVING_NONLIVING_ENERGY_TRANSPORT,
  '2/science/places-of-greece': GRADE2_SCIENCE_PLACES_OF_GREECE,
  '2/science/plants': GRADE2_SCIENCE_PLANTS,
  '2/science/school-neighbourhood-orientation': GRADE2_SCIENCE_SCHOOL_NEIGHBOURHOOD_ORIENTATION,
  '2/science/time-needs-rights': GRADE2_SCIENCE_TIME_NEEDS_RIGHTS,
  '2/science/water-weather': GRADE2_SCIENCE_WATER_WEATHER,
};
