/** Generated by `node scripts/school-units.mjs registry` — every written unit of this grade. */
import type { QuizQuestion } from '../../../types';
import { GRADE1_MATH_ADDITION_TO_10 } from './math-addition-to-10';
import { GRADE1_MATH_NUMBERS_TO_20 } from './math-numbers-to-20';

export const QUESTIONS: Record<string, QuizQuestion[]> = {
  '1/math/addition-to-10': GRADE1_MATH_ADDITION_TO_10,
  '1/math/numbers-to-20': GRADE1_MATH_NUMBERS_TO_20,
};
