/** Generated by `node scripts/school-units.mjs registry` — every written unit of this grade. */
import type { QuizQuestion } from '../../../types';
import { GRADE1_ELA_BLENDS_AND_DIGRAPHS } from './ela-blends-and-digraphs';
import { GRADE1_ELA_CAPITALS_AND_FULL_STOPS } from './ela-capitals-and-full-stops';
import { GRADE1_ELA_ONE_AND_MANY } from './ela-one-and-many';
import { GRADE1_ELA_PHONICS_SHORT_VOWELS } from './ela-phonics-short-vowels';
import { GRADE1_ELA_READING_LITTLE_STORIES } from './ela-reading-little-stories';
import { GRADE1_ELA_RHYMING_WORDS } from './ela-rhyming-words';
import { GRADE1_ELA_SIGHT_WORDS } from './ela-sight-words';
import { GRADE1_ENGLISH_ANIMALS } from './english-animals';
import { GRADE1_ENGLISH_CLASSROOM } from './english-classroom';
import { GRADE1_ENGLISH_COLOURS } from './english-colours';
import { GRADE1_ENGLISH_FOOD_I_LIKE } from './english-food-i-like';
import { GRADE1_ENGLISH_HELLO_GOODBYE } from './english-hello-goodbye';
import { GRADE1_ENGLISH_I_CAN } from './english-i-can';
import { GRADE1_ENGLISH_NUMBERS_1_10 } from './english-numbers-1-10';
import { GRADE1_GREEK_ACCENT_AND_QUESTION_MARK } from './greek-accent-and-question-mark';
import { GRADE1_GREEK_ARTICLES_GENDER } from './greek-articles-gender';
import { GRADE1_GREEK_DIGRAPHS } from './greek-digraphs';
import { GRADE1_GREEK_FIRST_WORDS } from './greek-first-words';
import { GRADE1_GREEK_LETTERS_SOUNDS } from './greek-letters-sounds';
import { GRADE1_GREEK_OPPOSITES_AND_WORD_FAMILIES } from './greek-opposites-and-word-families';
import { GRADE1_GREEK_READING_SIMPLE } from './greek-reading-simple';
import { GRADE1_GREEK_SENTENCES } from './greek-sentences';
import { GRADE1_GREEK_SYLLABLES } from './greek-syllables';
import { GRADE1_GREEK_VERBS_DOING_WORDS } from './greek-verbs-doing-words';
import { GRADE1_MATH_ADDITION_TO_10 } from './math-addition-to-10';
import { GRADE1_MATH_COINS_AND_TIME } from './math-coins-and-time';
import { GRADE1_MATH_COUNTING_PATTERNS } from './math-counting-patterns';
import { GRADE1_MATH_DOUBLES_AND_HALVES } from './math-doubles-and-halves';
import { GRADE1_MATH_MEASURING } from './math-measuring';
import { GRADE1_MATH_NUMBERS_TO_20 } from './math-numbers-to-20';
import { GRADE1_MATH_POSITION_AND_DIRECTION } from './math-position-and-direction';
import { GRADE1_MATH_SHAPES_AND_PATTERNS } from './math-shapes-and-patterns';
import { GRADE1_MATH_SUBTRACTION } from './math-subtraction';
import { GRADE1_MATH_TENS_AND_ONES } from './math-tens-and-ones';
import { GRADE1_MATH_WORD_PROBLEMS } from './math-word-problems';
import { GRADE1_SCIENCE_BODY_NEEDS_JOBS } from './science-body-needs-jobs';
import { GRADE1_SCIENCE_CLASS_SCHOOL_FAMILY } from './science-class-school-family';
import { GRADE1_SCIENCE_COMMUNICATION_CULTURE } from './science-communication-culture';
import { GRADE1_SCIENCE_HOME_NEIGHBOURHOOD_PLACE } from './science-home-neighbourhood-place';
import { GRADE1_SCIENCE_MATERIALS_ELECTRICITY_SOUND } from './science-materials-electricity-sound';
import { GRADE1_SCIENCE_PLANTS_ANIMALS } from './science-plants-animals';
import { GRADE1_SCIENCE_TIME_AND_SUN } from './science-time-and-sun';

export const QUESTIONS: Record<string, QuizQuestion[]> = {
  '1/ela/blends-and-digraphs': GRADE1_ELA_BLENDS_AND_DIGRAPHS,
  '1/ela/capitals-and-full-stops': GRADE1_ELA_CAPITALS_AND_FULL_STOPS,
  '1/ela/one-and-many': GRADE1_ELA_ONE_AND_MANY,
  '1/ela/phonics-short-vowels': GRADE1_ELA_PHONICS_SHORT_VOWELS,
  '1/ela/reading-little-stories': GRADE1_ELA_READING_LITTLE_STORIES,
  '1/ela/rhyming-words': GRADE1_ELA_RHYMING_WORDS,
  '1/ela/sight-words': GRADE1_ELA_SIGHT_WORDS,
  '1/english/animals': GRADE1_ENGLISH_ANIMALS,
  '1/english/classroom': GRADE1_ENGLISH_CLASSROOM,
  '1/english/colours': GRADE1_ENGLISH_COLOURS,
  '1/english/food-i-like': GRADE1_ENGLISH_FOOD_I_LIKE,
  '1/english/hello-goodbye': GRADE1_ENGLISH_HELLO_GOODBYE,
  '1/english/i-can': GRADE1_ENGLISH_I_CAN,
  '1/english/numbers-1-10': GRADE1_ENGLISH_NUMBERS_1_10,
  '1/greek/accent-and-question-mark': GRADE1_GREEK_ACCENT_AND_QUESTION_MARK,
  '1/greek/articles-gender': GRADE1_GREEK_ARTICLES_GENDER,
  '1/greek/digraphs': GRADE1_GREEK_DIGRAPHS,
  '1/greek/first-words': GRADE1_GREEK_FIRST_WORDS,
  '1/greek/letters-sounds': GRADE1_GREEK_LETTERS_SOUNDS,
  '1/greek/opposites-and-word-families': GRADE1_GREEK_OPPOSITES_AND_WORD_FAMILIES,
  '1/greek/reading-simple': GRADE1_GREEK_READING_SIMPLE,
  '1/greek/sentences': GRADE1_GREEK_SENTENCES,
  '1/greek/syllables': GRADE1_GREEK_SYLLABLES,
  '1/greek/verbs-doing-words': GRADE1_GREEK_VERBS_DOING_WORDS,
  '1/math/addition-to-10': GRADE1_MATH_ADDITION_TO_10,
  '1/math/coins-and-time': GRADE1_MATH_COINS_AND_TIME,
  '1/math/counting-patterns': GRADE1_MATH_COUNTING_PATTERNS,
  '1/math/doubles-and-halves': GRADE1_MATH_DOUBLES_AND_HALVES,
  '1/math/measuring': GRADE1_MATH_MEASURING,
  '1/math/numbers-to-20': GRADE1_MATH_NUMBERS_TO_20,
  '1/math/position-and-direction': GRADE1_MATH_POSITION_AND_DIRECTION,
  '1/math/shapes-and-patterns': GRADE1_MATH_SHAPES_AND_PATTERNS,
  '1/math/subtraction': GRADE1_MATH_SUBTRACTION,
  '1/math/tens-and-ones': GRADE1_MATH_TENS_AND_ONES,
  '1/math/word-problems': GRADE1_MATH_WORD_PROBLEMS,
  '1/science/body-needs-jobs': GRADE1_SCIENCE_BODY_NEEDS_JOBS,
  '1/science/class-school-family': GRADE1_SCIENCE_CLASS_SCHOOL_FAMILY,
  '1/science/communication-culture': GRADE1_SCIENCE_COMMUNICATION_CULTURE,
  '1/science/home-neighbourhood-place': GRADE1_SCIENCE_HOME_NEIGHBOURHOOD_PLACE,
  '1/science/materials-electricity-sound': GRADE1_SCIENCE_MATERIALS_ELECTRICITY_SOUND,
  '1/science/plants-animals': GRADE1_SCIENCE_PLANTS_ANIMALS,
  '1/science/time-and-sun': GRADE1_SCIENCE_TIME_AND_SUN,
};
