/** Generated by `node scripts/school-units.mjs registry` — every written unit of this grade. */
import type { QuizQuestion } from '../../../types';
import { GRADE6_ELA_ACTIVE_AND_PASSIVE_VOICE } from './ela-active-and-passive-voice';
import { GRADE6_ELA_CLAUSES_AND_CONJUNCTIONS } from './ela-clauses-and-conjunctions';
import { GRADE6_ELA_EDITING_AND_PROOFREADING } from './ela-editing-and-proofreading';
import { GRADE6_ELA_FORMAL_AND_INFORMAL } from './ela-formal-and-informal';
import { GRADE6_ELA_IDIOMS_AND_FIGURATIVE_LANGUAGE } from './ela-idioms-and-figurative-language';
import { GRADE6_ELA_SUMMARIZING } from './ela-summarizing';
import { GRADE6_ELA_VOCABULARY_IN_CONTEXT } from './ela-vocabulary-in-context';
import { GRADE6_ENGLISH_COUNTRIES_AND_LANGUAGES } from './english-countries-and-languages';
import { GRADE6_ENGLISH_EXPERIENCES } from './english-experiences';
import { GRADE6_ENGLISH_IMAGINARY_CREATURES } from './english-imaginary-creatures';
import { GRADE6_ENGLISH_INVENTIONS } from './english-inventions';
import { GRADE6_ENGLISH_JOBS_AND_FUTURE } from './english-jobs-and-future';
import { GRADE6_ENGLISH_SHOPPING } from './english-shopping';
import { GRADE6_ENGLISH_TRAVEL_AND_TRANSPORT } from './english-travel-and-transport';
import { GRADE6_GEOGRAPHY_AMERICAS_AND_OCEANIA } from './geography-americas-and-oceania';
import { GRADE6_GEOGRAPHY_ASIA_AND_AFRICA } from './geography-asia-and-africa';
import { GRADE6_GEOGRAPHY_CONTINENTS_AND_OCEANS } from './geography-continents-and-oceans';
import { GRADE6_GEOGRAPHY_EARTH_IN_SPACE } from './geography-earth-in-space';
import { GRADE6_GEOGRAPHY_EUROPE } from './geography-europe';
import { GRADE6_GEOGRAPHY_PEOPLE_OF_THE_WORLD } from './geography-people-of-the-world';
import { GRADE6_GEOGRAPHY_WORLD_MOUNTAINS_RIVERS } from './geography-world-mountains-rivers';
import { GRADE6_GREEK_ARGUMENTATION } from './greek-argumentation';
import { GRADE6_GREEK_ETYMOLOGY_AND_LEARNED_WORDS } from './greek-etymology-and-learned-words';
import { GRADE6_GREEK_NOUN_PHRASE } from './greek-noun-phrase';
import { GRADE6_GREEK_PASSIVE_SYNTAX } from './greek-passive-syntax';
import { GRADE6_GREEK_READING_CRITICAL } from './greek-reading-critical';
import { GRADE6_GREEK_SPEECH_AND_STYLE } from './greek-speech-and-style';
import { GRADE6_GREEK_SPELLING_MASTERY } from './greek-spelling-mastery';
import { GRADE6_GREEK_SUBORDINATE_CLAUSES } from './greek-subordinate-clauses';
import { GRADE6_GREEK_SYNTAX_CLAUSES } from './greek-syntax-clauses';
import { GRADE6_GREEK_VERB_SYSTEM } from './greek-verb-system';
import { GRADE6_GREEK_WORD_FORMATION } from './greek-word-formation';
import { GRADE6_HISTORY_BALKAN_WARS_VENIZELOS } from './history-balkan-wars-venizelos';
import { GRADE6_HISTORY_EUROPE_MODERN_TIMES } from './history-europe-modern-times';
import { GRADE6_HISTORY_GREECE_19TH_CENTURY } from './history-greece-19th-century';
import { GRADE6_HISTORY_MISSOLONGHI_TO_INDEPENDENCE } from './history-missolonghi-to-independence';
import { GRADE6_HISTORY_OTTOMAN_RULE } from './history-ottoman-rule';
import { GRADE6_HISTORY_REVOLUTION_1821 } from './history-revolution-1821';
import { GRADE6_HISTORY_WWII_TO_EUROPE } from './history-wwii-to-europe';
import { GRADE6_MATH_CIRCLE_LENGTH_AND_AREA } from './math-circle-length-and-area';
import { GRADE6_MATH_DATA_AND_GRAPHS } from './math-data-and-graphs';
import { GRADE6_MATH_EQUATIONS } from './math-equations';
import { GRADE6_MATH_FRACTIONS_ADVANCED } from './math-fractions-advanced';
import { GRADE6_MATH_GEOMETRY_AREA_VOLUME } from './math-geometry-area-volume';
import { GRADE6_MATH_MEASUREMENT_PATTERNS } from './math-measurement-patterns';
import { GRADE6_MATH_NUMBERS_AND_OPERATIONS } from './math-numbers-and-operations';
import { GRADE6_MATH_POWERS_AND_ROOTS } from './math-powers-and-roots';
import { GRADE6_MATH_PRIMES_GCD_LCM } from './math-primes-gcd-lcm';
import { GRADE6_MATH_RATIO_PROPORTION_PERCENT } from './math-ratio-proportion-percent';
import { GRADE6_MATH_SCALE_AND_MAPS } from './math-scale-and-maps';
import { GRADE6_SCIENCE_ACIDS_BASES_MICROBES } from './science-acids-bases-microbes';
import { GRADE6_SCIENCE_BODY_SYSTEMS } from './science-body-systems';
import { GRADE6_SCIENCE_ECOSYSTEMS } from './science-ecosystems';
import { GRADE6_SCIENCE_ELECTROMAGNETISM_LIGHT } from './science-electromagnetism-light';
import { GRADE6_SCIENCE_ENERGY_SOURCES } from './science-energy-sources';
import { GRADE6_SCIENCE_HEAT_TRANSFER } from './science-heat-transfer';
import { GRADE6_SCIENCE_LIFE_PLANTS_ANIMALS } from './science-life-plants-animals';

export const QUESTIONS: Record<string, QuizQuestion[]> = {
  '6/ela/active-and-passive-voice': GRADE6_ELA_ACTIVE_AND_PASSIVE_VOICE,
  '6/ela/clauses-and-conjunctions': GRADE6_ELA_CLAUSES_AND_CONJUNCTIONS,
  '6/ela/editing-and-proofreading': GRADE6_ELA_EDITING_AND_PROOFREADING,
  '6/ela/formal-and-informal': GRADE6_ELA_FORMAL_AND_INFORMAL,
  '6/ela/idioms-and-figurative-language': GRADE6_ELA_IDIOMS_AND_FIGURATIVE_LANGUAGE,
  '6/ela/summarizing': GRADE6_ELA_SUMMARIZING,
  '6/ela/vocabulary-in-context': GRADE6_ELA_VOCABULARY_IN_CONTEXT,
  '6/english/countries-and-languages': GRADE6_ENGLISH_COUNTRIES_AND_LANGUAGES,
  '6/english/experiences': GRADE6_ENGLISH_EXPERIENCES,
  '6/english/imaginary-creatures': GRADE6_ENGLISH_IMAGINARY_CREATURES,
  '6/english/inventions': GRADE6_ENGLISH_INVENTIONS,
  '6/english/jobs-and-future': GRADE6_ENGLISH_JOBS_AND_FUTURE,
  '6/english/shopping': GRADE6_ENGLISH_SHOPPING,
  '6/english/travel-and-transport': GRADE6_ENGLISH_TRAVEL_AND_TRANSPORT,
  '6/geography/americas-and-oceania': GRADE6_GEOGRAPHY_AMERICAS_AND_OCEANIA,
  '6/geography/asia-and-africa': GRADE6_GEOGRAPHY_ASIA_AND_AFRICA,
  '6/geography/continents-and-oceans': GRADE6_GEOGRAPHY_CONTINENTS_AND_OCEANS,
  '6/geography/earth-in-space': GRADE6_GEOGRAPHY_EARTH_IN_SPACE,
  '6/geography/europe': GRADE6_GEOGRAPHY_EUROPE,
  '6/geography/people-of-the-world': GRADE6_GEOGRAPHY_PEOPLE_OF_THE_WORLD,
  '6/geography/world-mountains-rivers': GRADE6_GEOGRAPHY_WORLD_MOUNTAINS_RIVERS,
  '6/greek/argumentation': GRADE6_GREEK_ARGUMENTATION,
  '6/greek/etymology-and-learned-words': GRADE6_GREEK_ETYMOLOGY_AND_LEARNED_WORDS,
  '6/greek/noun-phrase': GRADE6_GREEK_NOUN_PHRASE,
  '6/greek/passive-syntax': GRADE6_GREEK_PASSIVE_SYNTAX,
  '6/greek/reading-critical': GRADE6_GREEK_READING_CRITICAL,
  '6/greek/speech-and-style': GRADE6_GREEK_SPEECH_AND_STYLE,
  '6/greek/spelling-mastery': GRADE6_GREEK_SPELLING_MASTERY,
  '6/greek/subordinate-clauses': GRADE6_GREEK_SUBORDINATE_CLAUSES,
  '6/greek/syntax-clauses': GRADE6_GREEK_SYNTAX_CLAUSES,
  '6/greek/verb-system': GRADE6_GREEK_VERB_SYSTEM,
  '6/greek/word-formation': GRADE6_GREEK_WORD_FORMATION,
  '6/history/balkan-wars-venizelos': GRADE6_HISTORY_BALKAN_WARS_VENIZELOS,
  '6/history/europe-modern-times': GRADE6_HISTORY_EUROPE_MODERN_TIMES,
  '6/history/greece-19th-century': GRADE6_HISTORY_GREECE_19TH_CENTURY,
  '6/history/missolonghi-to-independence': GRADE6_HISTORY_MISSOLONGHI_TO_INDEPENDENCE,
  '6/history/ottoman-rule': GRADE6_HISTORY_OTTOMAN_RULE,
  '6/history/revolution-1821': GRADE6_HISTORY_REVOLUTION_1821,
  '6/history/wwii-to-europe': GRADE6_HISTORY_WWII_TO_EUROPE,
  '6/math/circle-length-and-area': GRADE6_MATH_CIRCLE_LENGTH_AND_AREA,
  '6/math/data-and-graphs': GRADE6_MATH_DATA_AND_GRAPHS,
  '6/math/equations': GRADE6_MATH_EQUATIONS,
  '6/math/fractions-advanced': GRADE6_MATH_FRACTIONS_ADVANCED,
  '6/math/geometry-area-volume': GRADE6_MATH_GEOMETRY_AREA_VOLUME,
  '6/math/measurement-patterns': GRADE6_MATH_MEASUREMENT_PATTERNS,
  '6/math/numbers-and-operations': GRADE6_MATH_NUMBERS_AND_OPERATIONS,
  '6/math/powers-and-roots': GRADE6_MATH_POWERS_AND_ROOTS,
  '6/math/primes-gcd-lcm': GRADE6_MATH_PRIMES_GCD_LCM,
  '6/math/ratio-proportion-percent': GRADE6_MATH_RATIO_PROPORTION_PERCENT,
  '6/math/scale-and-maps': GRADE6_MATH_SCALE_AND_MAPS,
  '6/science/acids-bases-microbes': GRADE6_SCIENCE_ACIDS_BASES_MICROBES,
  '6/science/body-systems': GRADE6_SCIENCE_BODY_SYSTEMS,
  '6/science/ecosystems': GRADE6_SCIENCE_ECOSYSTEMS,
  '6/science/electromagnetism-light': GRADE6_SCIENCE_ELECTROMAGNETISM_LIGHT,
  '6/science/energy-sources': GRADE6_SCIENCE_ENERGY_SOURCES,
  '6/science/heat-transfer': GRADE6_SCIENCE_HEAT_TRANSFER,
  '6/science/life-plants-animals': GRADE6_SCIENCE_LIFE_PLANTS_ANIMALS,
};
